/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package voyage;

import classes.Client;
import classes.Reservation;
import gestion.GestionClient;
import gestion.GestionReservation;
import java.awt.Choice;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Modifier extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private final String id ;
    private final String code_res ;
    public Modifier(String id, String code_res) {
        initComponents();
        this.id = id ;
        this.code_res = code_res ;
        ajouterElementCombo();
        remplirDonnee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelCover1 = new app.component.PanelCover();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sexeRadio1 = new javax.swing.JRadioButton();
        sexeRadio2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        prenomField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        adresseField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cinField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        classe1 = new javax.swing.JRadioButton();
        classe2 = new javax.swing.JRadioButton();
        classeVIP = new javax.swing.JRadioButton();
        nbrPlace = new javax.swing.JSpinner();
        montant = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateVoyage = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        heureDepart = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        villeDepart = new javax.swing.JComboBox();
        villeArrivee = new javax.swing.JComboBox();
        ajouterBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("e-voyage");

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acceuil");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(92, 0, 0, 0);
        jPanel5.add(jLabel1, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ajouter reservation");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        jPanel5.add(jLabel3, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 207, 250));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("liste reservation");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        jPanel5.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Statistiques");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        jPanel5.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Deconnecter");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 72, 0);
        jPanel5.add(jLabel6, gridBagConstraints);

        javax.swing.GroupLayout panelCover1Layout = new javax.swing.GroupLayout(panelCover1);
        panelCover1.setLayout(panelCover1Layout);
        panelCover1Layout.setHorizontalGroup(
            panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCover1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCover1Layout.setVerticalGroup(
            panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCover1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(242, 246, 250));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        sexeRadio1.setBackground(new java.awt.Color(255, 255, 255));
        sexeRadio1.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        sexeRadio1.setForeground(new java.awt.Color(42, 245, 152));
        sexeRadio1.setText("Homme");
        sexeRadio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sexeRadio1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 86, 0, 0);
        jPanel2.add(sexeRadio1, gridBagConstraints);

        sexeRadio2.setBackground(new java.awt.Color(255, 255, 255));
        sexeRadio2.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        sexeRadio2.setForeground(new java.awt.Color(42, 245, 152));
        sexeRadio2.setText("Femme");
        sexeRadio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sexeRadio2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 32, 0, 0);
        jPanel2.add(sexeRadio2, gridBagConstraints);

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 207, 250));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INFORMATIONS PERSONNELLES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 10, 0, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        nomField.setBackground(new java.awt.Color(249, 255, 255));
        nomField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nomField.setMaximumSize(new java.awt.Dimension(6, 20));
        nomField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomFieldFocusLost(evt);
            }
        });
        nomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldActionPerformed(evt);
            }
        });
        nomField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 308;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel2.add(nomField, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 207, 250));
        jLabel17.setText("Nom :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel2.add(jLabel17, gridBagConstraints);

        prenomField.setBackground(new java.awt.Color(249, 255, 255));
        prenomField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        prenomField.setMaximumSize(new java.awt.Dimension(6, 20));
        prenomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomFieldActionPerformed(evt);
            }
        });
        prenomField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prenomFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 308;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel2.add(prenomField, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 207, 250));
        jLabel18.setText("Prenom :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 131;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel2.add(jLabel18, gridBagConstraints);

        adresseField.setBackground(new java.awt.Color(249, 255, 255));
        adresseField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adresseField.setMaximumSize(new java.awt.Dimension(6, 20));
        adresseField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adresseFieldFocusLost(evt);
            }
        });
        adresseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresseFieldActionPerformed(evt);
            }
        });
        adresseField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adresseFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 308;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel2.add(adresseField, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 207, 250));
        jLabel19.setText("Adresse :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        jPanel2.add(jLabel19, gridBagConstraints);

        cinField.setBackground(new java.awt.Color(249, 255, 255));
        cinField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cinField.setMaximumSize(new java.awt.Dimension(6, 20));
        cinField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cinFieldFocusLost(evt);
            }
        });
        cinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinFieldActionPerformed(evt);
            }
        });
        cinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cinFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 308;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 29, 0);
        jPanel2.add(cinField, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 207, 250));
        jLabel20.setText("Numero CIN  :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel2.add(jLabel20, gridBagConstraints);

        phoneField.setBackground(new java.awt.Color(249, 255, 255));
        phoneField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        phoneField.setMaximumSize(new java.awt.Dimension(6, 20));
        phoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFieldFocusLost(evt);
            }
        });
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 308;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel2.add(phoneField, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 207, 250));
        jLabel21.setText("Téléphone :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel2.add(jLabel21, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 207, 250));
        jLabel22.setText("Id du client :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        jPanel2.add(jLabel22, gridBagConstraints);

        idField.setBackground(new java.awt.Color(249, 255, 255));
        idField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        idField.setMaximumSize(new java.awt.Dimension(6, 20));
        idField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFieldFocusLost(evt);
            }
        });
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        idField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 308;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel2.add(idField, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(242, 246, 250));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 207, 250));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INFORMATIONS DU VOYAGE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 71, 0, 0);
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 207, 250));
        jLabel10.setText("Nombre de places à résérver :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 56, 0, 0);
        jPanel3.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 207, 250));
        jLabel11.setText("classe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 56, 0, 0);
        jPanel3.add(jLabel11, gridBagConstraints);

        classe1.setBackground(new java.awt.Color(255, 255, 255));
        classe1.setForeground(new java.awt.Color(42, 245, 152));
        classe1.setText("1er classe");
        classe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classe1MouseClicked(evt);
            }
        });
        classe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classe1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 18, 7, 0);
        jPanel3.add(classe1, gridBagConstraints);

        classe2.setBackground(new java.awt.Color(255, 255, 255));
        classe2.setForeground(new java.awt.Color(42, 245, 152));
        classe2.setText("2ème classe");
        classe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classe2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 13, 7, 0);
        jPanel3.add(classe2, gridBagConstraints);

        classeVIP.setBackground(new java.awt.Color(255, 255, 255));
        classeVIP.setForeground(new java.awt.Color(42, 245, 152));
        classeVIP.setText("VIP");
        classeVIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classeVIPMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 18, 7, 61);
        jPanel3.add(classeVIP, gridBagConstraints);

        nbrPlace.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nbrPlaceStateChanged(evt);
            }
        });
        nbrPlace.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nbrPlaceFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 61);
        jPanel3.add(nbrPlace, gridBagConstraints);

        montant.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                montantStateChanged(evt);
            }
        });
        montant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                montantFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 2, 0, 61);
        jPanel3.add(montant, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 207, 250));
        jLabel24.setText("Montant unitaire :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 0);
        jPanel3.add(jLabel24, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(242, 246, 250));
        jPanel4.setToolTipText("");
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 207, 250));
        jLabel12.setText("Ville depart :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 53, 0, 0);
        jPanel4.add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 207, 250));
        jLabel13.setText("Ville arrivée :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 53, 0, 0);
        jPanel4.add(jLabel13, gridBagConstraints);

        dateVoyage.setBackground(new java.awt.Color(249, 255, 255));
        dateVoyage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dateVoyage.setMaximumSize(new java.awt.Dimension(6, 20));
        dateVoyage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateVoyageFocusLost(evt);
            }
        });
        dateVoyage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateVoyageActionPerformed(evt);
            }
        });
        dateVoyage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateVoyageKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 294;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 0, 76);
        jPanel4.add(dateVoyage, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 207, 250));
        jLabel14.setText("Date du voyage :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 0, 0);
        jPanel4.add(jLabel14, gridBagConstraints);

        heureDepart.setBackground(new java.awt.Color(249, 255, 255));
        heureDepart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        heureDepart.setMaximumSize(new java.awt.Dimension(6, 20));
        heureDepart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                heureDepartFocusLost(evt);
            }
        });
        heureDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heureDepartActionPerformed(evt);
            }
        });
        heureDepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                heureDepartKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 294;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 11, 76);
        jPanel4.add(heureDepart, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 207, 250));
        jLabel15.setText("Heure de depart souhaité :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 53, 0, 0);
        jPanel4.add(jLabel15, gridBagConstraints);

        villeDepart.setBackground(new java.awt.Color(249, 255, 255));
        villeDepart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 244;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 0, 76);
        jPanel4.add(villeDepart, gridBagConstraints);

        villeArrivee.setBackground(new java.awt.Color(249, 255, 255));
        villeArrivee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 244;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 53, 0, 76);
        jPanel4.add(villeArrivee, gridBagConstraints);

        ajouterBtn.setBackground(new java.awt.Color(42, 245, 152));
        ajouterBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ajouterBtn.setForeground(new java.awt.Color(255, 255, 255));
        ajouterBtn.setText("VALIDER");
        ajouterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajouterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterBtnMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 207, 250));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REINITIALISER");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(panelCover1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ajouterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
            .addComponent(panelCover1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1.setLayer(panelCover1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ajouterBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterElementCombo(){
        villeArrivee.removeAllItems();
        villeDepart.removeAllItems();
        villeArrivee.addItem("Tananarive");
        villeArrivee.addItem("Fianarantsoa");
        villeArrivee.addItem("Tulear");
        villeArrivee.addItem("Majunga");
        villeArrivee.addItem("Tamatave");
        villeArrivee.addItem("Antsiranana");
        
        villeDepart.addItem("Fianarantsoa");
        villeDepart.addItem("Tananarive");
        villeDepart.addItem("Tulear");
        villeDepart.addItem("Majunga");
        villeDepart.addItem("Tamatave");
        villeDepart.addItem("Antsiranana");
    }
    private void remplirDonnee(){
        try{
            gestion.GestionReservation g1 = new GestionReservation();
            ResultSet rs1;
            rs1 = g1.getAllDonnee(id,code_res);
            while (rs1.next()){
                idField.setText(rs1.getString("id_client"));
                nomField.setText(rs1.getString("nom"));
                prenomField.setText(rs1.getString("prenom"));
                adresseField.setText(rs1.getString("adresse"));
                cinField.setText(rs1.getString("cin"));
                phoneField.setText(rs1.getString("telephone"));
                nbrPlace.setValue(Integer.valueOf(rs1.getString("nombre_place")));
                dateVoyage.setText(rs1.getString("date_voyage"));
                heureDepart.setText(rs1.getString("heure_depart"));
                if("M".equals(rs1.getString("sexe"))){ sexeRadio1.setSelected(true);
                }else{ sexeRadio2.setSelected(true); }
                if ("Premier classe".equals(rs1.getString("classe"))){ classe1.setSelected(true);
                } else if ("Deuxieme classe".equals(rs1.getString("classe"))){ classe2.setSelected(true);
                } else{classeVIP.setSelected(true);}
                villeDepart.setSelectedItem(rs1.getString("ville_depart"));
                villeArrivee.setSelectedItem(rs1.getString("ville_arrivee"));
                montant.setValue(Integer.valueOf(rs1.getString("montant")) );
            }
        }catch(Exception ex){
            ex.printStackTrace() ;
        }
    }
    private void classe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classe1ActionPerformed

    private void nbrPlaceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nbrPlaceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nbrPlaceFocusLost

    private void heureDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heureDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heureDepartActionPerformed

    private void dateVoyageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateVoyageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateVoyageActionPerformed

    private void nomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldActionPerformed

    private void prenomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomFieldActionPerformed

    private void adresseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseFieldActionPerformed

    private void cinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new App().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
        JOptionPane.showMessageDialog(null,"Vous êtes deconnecté !");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void nomFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomFieldKeyPressed
        // TODO add your handling code here:
        String valeur=nomField.getText();
        int ln =valeur.length();
        if(nomField.getText().matches("[A-Z]*") && ln < 40){//ok
            nomField.setText(valeur);
        }else{//non ok
            valeur = valeur.substring(0,ln-1);
            nomField.setText(valeur);
        }
    }//GEN-LAST:event_nomFieldKeyPressed

    private void cinFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinFieldKeyPressed
        // TODO add your handling code here:
        String valeur=cinField.getText();
        int ln =valeur.length();
        if(cinField.getText().matches("[0-9]*")){//ok
            if(ln>12){
                valeur = valeur.substring(0,ln-1);
            }
            cinField.setText(valeur);
        }else{//non ok
            valeur = valeur.substring(0,ln-1);
            cinField.setText(valeur);
        }
    }//GEN-LAST:event_cinFieldKeyPressed

    private void cinFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFieldFocusLost
        // TODO add your handling code here:
        String valeur=cinField.getText();
        int ln =valeur.length();
        if (ln == 0){
        
        }
        else if (ln!=12){            
            cinField.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null,"Numéro de CIN invalide , (doit être 12)");
             cinField.setBackground(new Color(249,255,255));
             cinField.requestFocus();
        }
    }//GEN-LAST:event_cinFieldFocusLost

    private void nomFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFieldFocusLost
        // TODO add your handling code here:
        String valeur=nomField.getText();
        int ln =valeur.length();
        if (ln == 0){
        
        }
        else if (ln<3){            
            nomField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Nom trop court , et doit être en majuscule");
             nomField.setBackground(new Color(249,255,255));
             nomField.requestFocus();
        }
    }//GEN-LAST:event_nomFieldFocusLost

    private void prenomFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomFieldKeyPressed
        // TODO add your handling code here:
        String valeur=prenomField.getText();
        int ln =valeur.length();
        if(prenomField.getText().matches("[A-Za-z]*") && ln < 50){//ok
            prenomField.setText(valeur);
        }else{//non ok
            valeur = valeur.substring(0,ln-1);
            prenomField.setText(valeur);
        }
    }//GEN-LAST:event_prenomFieldKeyPressed

    private void phoneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyPressed
        // TODO add your handling code here:
        String valeur=phoneField.getText();
        int ln =valeur.length();
        if(phoneField.getText().matches("[0-9]*") && ln < 11){//ok
            phoneField.setText(valeur);
        }else{//non ok
            valeur = valeur.substring(0,ln-1);
            phoneField.setText(valeur);
        }
    }//GEN-LAST:event_phoneFieldKeyPressed

    private void phoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusLost
        // TODO add your handling code here:
        String valeur=phoneField.getText();
        int ln =valeur.length();
        if (ln == 0){
        
        }
        else if (ln != 10){     
            phoneField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Telephone invalide");
             phoneField.setBackground(new Color(249,255,255));
             phoneField.requestFocus();
        }
    }//GEN-LAST:event_phoneFieldFocusLost

    private void adresseFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresseFieldKeyPressed
        // TODO add your handling code here:
        String valeur=adresseField.getText();
        int ln =valeur.length();
        if(adresseField.getText().matches("[A-Za-z0-9 ]*") && ln < 50){//ok
            adresseField.setText(valeur);
        }else{//non ok
            valeur = valeur.substring(0,ln-1);
            adresseField.setText(valeur);
        }
    }//GEN-LAST:event_adresseFieldKeyPressed

    private void adresseFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adresseFieldFocusLost
        // TODO add your handling code here:
        String valeur=adresseField.getText();
        int ln =valeur.length();
        if (ln == 0){
        
        }
        else if (ln < 4){           
            adresseField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Adresse invalide !");
             adresseField.setBackground(new Color(249,255,255));
             adresseField.requestFocus();
        }
    }//GEN-LAST:event_adresseFieldFocusLost

    private void ajouterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterBtnMouseClicked
        if(idField.getText().length() == 0){JOptionPane.showMessageDialog(null,"Veuiller completer le champ du ID !");
        }else{if(nomField.getText().length() == 0){JOptionPane.showMessageDialog(null,"Veuiller completer le champ du nom !");
            }else{if(adresseField.getText().length() == 0){JOptionPane.showMessageDialog(null,"Veuiller completer le champ d'adressee !");
                }else{if(phoneField.getText().length() == 0){JOptionPane.showMessageDialog(null,"Veuiller completer le champ du telephone !");
                    }else{if(cinField.getText().length() == 0){JOptionPane.showMessageDialog(null,"Veuiller completer le champ du CIN !");
                        }else{if((int)nbrPlace.getValue() == 0){JOptionPane.showMessageDialog(null,"Nombre de place invalide !");
                            }else{if((int)montant.getValue() == 0){JOptionPane.showMessageDialog(null,"Montant invalide !");
                               }else{if(dateVoyage.getText().length() == 0){JOptionPane.showMessageDialog(null,"Veuiller completer le champ date voyage !");
                                }else{if(heureDepart.getText().length() == 0){JOptionPane.showMessageDialog(null,"Veuiller completer le champ heure depart !");
                                    }else{if(villeArrivee.getSelectedItem() == villeDepart.getSelectedItem()){JOptionPane.showMessageDialog(null,"Selectionnez differentes ville depart et arrivée ! ");
                                        }else{
                                           String sexe = sexeRadio1.isSelected() ? "M" : "F" ;
                                            String classeVoyage = null ;
                                            if (classe1.isSelected()){
                                                classeVoyage = "Premier classe" ;
                                            } else if(classe2.isSelected()){
                                                classeVoyage = "Deuxieme classe" ;
                                            } else if(classeVIP.isSelected()){
                                                classeVoyage = "VIP classe";
                                            }
                                            String nb = nbrPlace.getValue().toString();
                                            String idClient = idField.getText() ;
                                            int total = (int)nbrPlace.getValue() * (int)montant.getValue() ;
                                            Client c1 = new Client(idField.getText(),nomField.getText(),prenomField.getText(),sexe,adresseField.getText(),cinField.getText(), phoneField.getText());
                                            Reservation r1 = new Reservation(nb, classeVoyage, villeDepart.getSelectedItem().toString(), villeArrivee.getSelectedItem().toString(), dateVoyage.getText(), heureDepart.getText(),montant.getValue().toString(),String.valueOf(total) , idClient) ;
                                            try {
                                                gestion.GestionClient gp = new GestionClient();
                                                gp.update(id , c1);
                                                JOptionPane.showMessageDialog(null,"Client modifié !");
                                            }catch(Exception e){
                                                System.err.println("errreur : " + e);
                                            } 
                                            try {
                                                gestion.GestionReservation gr = new GestionReservation();
                                                gr.update(id ,code_res, r1);
                                                JOptionPane.showMessageDialog(null,"Reservation modifié !");
                                            }catch(Exception e){
                                                System.err.println("errreur : " + e);
                                            } 
                                            setVisible(false);
                                            new Liste().setVisible(true);
                                        }  
                                    }
                                }
                            }
                        }
                    }
                    }
                }
            }
        }
    }//GEN-LAST:event_ajouterBtnMouseClicked

    private void sexeRadio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexeRadio1MouseClicked
        sexeRadio2.setSelected(false);
        sexeRadio1.setSelected(true); 
    }//GEN-LAST:event_sexeRadio1MouseClicked

    private void sexeRadio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexeRadio2MouseClicked
        sexeRadio1.setSelected(false);
        sexeRadio2.setSelected(true);
    }//GEN-LAST:event_sexeRadio2MouseClicked

    private void classe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classe1MouseClicked
        classe2.setSelected(false);
        classeVIP.setSelected(false);
        classe1.setSelected(true);
    }//GEN-LAST:event_classe1MouseClicked

    private void classe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classe2MouseClicked
        classe1.setSelected(false);
        classeVIP.setSelected(false);
        classe2.setSelected(true);
    }//GEN-LAST:event_classe2MouseClicked

    private void classeVIPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classeVIPMouseClicked
        classe2.setSelected(false);
        classe1.setSelected(false);
        classeVIP.setSelected(true);
    }//GEN-LAST:event_classeVIPMouseClicked

    private void nbrPlaceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nbrPlaceStateChanged
        if((int)nbrPlace.getValue() < 0){
            nbrPlace.setValue(0);
        }
        else if((int)nbrPlace.getValue() > 23){
            nbrPlace.setValue(23);
        }
    }//GEN-LAST:event_nbrPlaceStateChanged

    private void dateVoyageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateVoyageKeyPressed
        String valeur=dateVoyage.getText();
        int ln =valeur.length();
        if(dateVoyage.getText().matches("[0-9-]*") && ln < 11){//ok
            if(ln == 2 || ln == 5){
                dateVoyage.setText(valeur + "-");
            } else {
                dateVoyage.setText(valeur );
            }
        }else{//non ok
            valeur = valeur.substring(0,ln-1);
            dateVoyage.setText(valeur);
        }
    }//GEN-LAST:event_dateVoyageKeyPressed

    private void idFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusLost
        String valeur=idField.getText();
        int ln =valeur.length();
        if (ln == 0){
        
        }
        else if (ln > 10){     
            idField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Id trop long");
             idField.setBackground(new Color(249,255,255));
             idField.requestFocus();
        }
    }//GEN-LAST:event_idFieldFocusLost

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void idFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idFieldKeyPressed
        String valeur=idField.getText();
        int ln =valeur.length();
        if(idField.getText().matches("[0-9]*") && ln < 11){//ok
            idField.setText(valeur);
        }else{//non ok
            valeur = valeur.substring(0,ln-1);
            idField.setText(valeur);
        }
    }//GEN-LAST:event_idFieldKeyPressed

    private void heureDepartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heureDepartKeyPressed
        String valeur=heureDepart.getText();
        int ln =valeur.length();
        if(heureDepart.getText().matches("[0-9a-z]*") && ln < 4){//ok
            heureDepart.setText(valeur);
        }else{//non ok
            valeur = valeur.substring(0,ln-1);
            heureDepart.setText(valeur);
        }
    }//GEN-LAST:event_heureDepartKeyPressed

    private void heureDepartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heureDepartFocusLost
        String valeur=heureDepart.getText();
        int ln =valeur.length();
        if (ln == 0){
        
        }
        if ( "07h".equals(valeur) || "09h".equals(valeur) || "18h".equals(valeur) || "20h".equals(valeur) ){     
            
        } else{
            heureDepart.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Choisissez dans nos heures de depart : 07h , 09h , 18h , 20h");
             heureDepart.setBackground(new Color(249,255,255));
             heureDepart.requestFocus();
        }
    }//GEN-LAST:event_heureDepartFocusLost

    private void dateVoyageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateVoyageFocusLost
        String valeur=dateVoyage.getText();
        int ln =valeur.length();
        if (ln == 0){
        
        }
        else if (ln > 10){     
            dateVoyage.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Id trop long");
             dateVoyage.setBackground(new Color(249,255,255));
             dateVoyage.requestFocus();
        }
    }//GEN-LAST:event_dateVoyageFocusLost

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setVisible(false);
        new Stats().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        setVisible(false);
        new Liste().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void montantStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_montantStateChanged
        // TODO add your handling code here:
        if((int)montant.getValue() < 0){
            montant.setValue(0);
        }
    }//GEN-LAST:event_montantStateChanged

    private void montantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montantFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_montantFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresseField;
    private javax.swing.JButton ajouterBtn;
    private javax.swing.JTextField cinField;
    private javax.swing.JRadioButton classe1;
    private javax.swing.JRadioButton classe2;
    private javax.swing.JRadioButton classeVIP;
    private javax.swing.JTextField dateVoyage;
    private javax.swing.JTextField heureDepart;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner montant;
    private javax.swing.JSpinner nbrPlace;
    private javax.swing.JTextField nomField;
    private app.component.PanelCover panelCover1;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField prenomField;
    private javax.swing.JRadioButton sexeRadio1;
    private javax.swing.JRadioButton sexeRadio2;
    private javax.swing.JComboBox villeArrivee;
    private javax.swing.JComboBox villeDepart;
    // End of variables declaration//GEN-END:variables
}
